config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'static_pages#top'
  get  '/signup', to: 'users#new'

  get     '/login', to: 'sessions#new'
  post    '/login', to: 'sessions#create'
  delete  '/logout', to: 'sessions#destroy'

  resources :users do
    member do
      get 'admin_post'
      post 'admin_pref_topic_post'
      post 'admin_city_topic_post'
    end
    resources :drafts
  end

  resources :gov_topics

  resources :prefs do
    member do
      get 'admin_index'
    end
    collection do
      get 'cities_select' # /prefs/cities_select
    end
    collection {post :import}
      resources :pref_topics
      resources :cities do
        member do
          get 'admin_index'
        end
        collection {post :import}
        resources :city_topics
      end
  end
  #get 'city_topics/new'
  #get 'city_topics/edit'
  #get 'city_topics/show'
  #get 'city_topics/index'
  #get 'pref_topics/new'
  #get 'pref_topics/edit'
  #get 'pref_topics/show'
  #get 'pref_topics/index'
  #get 'prefs/index'
  #get 'prefs/show'
  #get 'gov_topics/new'
  #get 'gov_topics/edit'
  #get 'gov_topics/show'
  #get 'gov_topics/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_many :drafts, dependent: :destroy
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 100 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  
  # 渡された文字列のハッシュ値を返します。
  def User.digest(string)
    cost =
      if ActiveModel::SecurePassword.min_cost
        BCrypt::Engine::MIN_COST
      else
        BCrypt::Engine.cost
      end
    BCrypt::Password.create(string, cost: cost)
  end
  
  # ランダムなトークンを返します。
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  # 永続セッションのためハッシュ化したトークンをデータベースに記憶します。
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  # トークンがダイジェストと一致すればtrueを返します。
  def authenticated?(remember_token)
    # ダイジェストが存在しない場合はfalseを返して終了します。
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # ユーザーのログイン情報を破棄します。
  def forget
    update_attribute(:remember_digest, nil)
  end
  
  def self.search(search)
    if search
      where(['name LIKE ?', "%#{search}%"])
    else
      all
    end
  end
  
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      # IDが見つかれば、レコードを呼び出し、見つからなければ、新しく作成
      user = find_by(id: row["id"]) || new
      # CSVからデータを取得し、設定する
      user.attributes = row.to_hash.slice(*updatable_attributes)
      # 保存する
      user.save
    end
  end
  
  # 更新を許可するカラムを定義
  def self.updatable_attributes
    ["id", "name", "email", "password"]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :admin_post]
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy, :admin_post]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: [:index, :destroy, :admin_post]
  before_action :admin_or_correct_user, only: [:show, :edit, :update]
  
  def index
    @user = User.search(params[:search])
    @title = "ユーザー一覧"
      if params.has_key?(:search)
        @title = "検索結果"
      end
    @users = User.paginate(page: params[:page])
  end
  
  def show
    
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = '新規作成に成功しました。'
      redirect_to @user
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "ユーザー情報を更新しました。"
      redirect_to @user
    else
      render :edit  
    end
  end
  
  def destroy
    @user.destroy
    flash[:success] = "#{@user.name}のデータを削除しました。"
    redirect_to users_url
  end

  def admin_post
    @gov_topic = GovTopic.new
    @prefs = Pref.all
    @pref_topic = PrefTopic.new
    @cities = Pref.all
    @city_topic = CityTopic.new
  end

  def admin_pref_topic_post
  end



  def admin_city_topic_post
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
    
    def admin_or_correct_user
    @user = User.find(params[:id]) if @user.blank?
      unless current_user?(@user) || current_user.admin?
        flash[:danger] = "アクセス権限がありません。"
        redirect_to(root_url)
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_cities.html.erb
<%= collection_select :city, :city, City.where(pref_id: pref_id), :id, :city_name %>

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |f| %>
  <%= render 'shared/error_messages', object: @user %>
  
  <%= f.label :name, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :name, class: "form-control" %>
  
  <%= f.label :email, class: "label-#{yield(:class_text)}" %>
  <%= f.email_field :email, class: "form-control" %>
  
  <%= f.label :password, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password, class: "form-control" %>
  
  <%= f.label :password_confirmation, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password_confirmation, class: "form-control" %>
  
  <%= f.submit yield(:button_text), class: "btn btn-primary btn-block btn-signup btn-#{yield(:button_text)}" %>
<% end %>

app/views/users/admin_post.html.erb
<h1>マスタ投稿画面</h1>

<div class="row">
  <div class="col-md-10 col-md-offset-1 col-xs-12 gov_background">
    <h3 class="center">国</h3>
    <%= form_with(model: @gov_topic, url: gov_topics_path, method: :post, local: true) do |f| %>

      <div class="col-md-10 col-md-offset-1 col-xs-12">
        <%= f.label "実施官公庁名" %>
        <%= f.text_field :gov_name, class: 'form-control' %>

        <%= f.label "施作名" %>
        <%= f.text_field :title, class: 'form-control' %>

        <%= f.label "実施期間" %>
        <%= f.text_field :period, class: 'form-control' %>

        <%= f.label "実施内容" %>
        <%= f.text_area :content, class: 'form-control' %>

        <%= f.label "対象者" %>
        <%= f.text_field :target, class: 'form-control' %>

        <%= f.label "受付窓口" %>
        <%= f.text_field :counter, class: 'form-control' %>

        <%= f.label "リンク" %>
        <%= f.text_field :link, class: 'form-control' %>

      </div>

      <div class="col-md-10 col-md-offset-1 col-xs-12">
        <%= f.label "カテゴリー" %><br>
        <%= f.check_box :emergency, {}, "true", "false" %>
        <span>緊急時（自然災害・感染症対策等）</span><br>
        <%= f.check_box :primary_sector, {}, "true", "false" %>
        <span>農林漁業者向け</span><br>
        <%= f.check_box :other_sector, {}, "true", "false" %>
        <span>その他事業者向け</span><br>
        <%= f.check_box :emigration, {}, "true", "false" %>
        <span>移住者向け</span><br>
        <%= f.check_box :senior, {}, "true", "false" %>
        <span>高齢者向け</span><br>
        <%= f.check_box :parenting, {}, "true", "false" %>
        <span>子育て世帯向け</span><br>
        <%= f.check_box :other, {checked: true}, "true", "false" %>
        <span>それ以外</span>
        <br>
        
      <%= f.submit "マスタ投稿", class: "btn btn-primary btn-block btn-login" %>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="col-md-10 col-md-offset-1 col-xs-12 pref_background">
    <h3 class="center">県</h3>
    <%= form_with(model: @prefs, url: admin_pref_topic_post_user_path(@user), local: true) do |pref| %>

      <div class="col-md-10 col-md-offset-1 col-xs-12">
        <%= pref.label "実施官公庁名" %>
        <%= pref.collection_select :pref_code, Pref.all, :id, :pref_name, {prompt: "選択して下さい"} %><br>

        <%= pref.fields_for "pref_topics[]", @pref_topic do |f| %>

        <%= f.label "施作名" %>
        <%= f.text_field :title, class: 'form-control' %>

        <%= f.label "実施期間" %>
        <%= f.text_field :period, class: 'form-control' %>

        <%= f.label "実施内容" %>
        <%= f.text_area :content, class: 'form-control' %>

        <%= f.label "対象者" %>
        <%= f.text_field :target, class: 'form-control' %>

        <%= f.label "受付窓口" %>
        <%= f.text_field :counter, class: 'form-control' %>

        <%= f.label "リンク" %>
        <%= f.text_field :link, class: 'form-control' %>

      </div>

      <div class="col-md-10 col-md-offset-1 col-xs-12">
        <%= f.label "カテゴリー" %><br>
        <%= f.check_box :emergency, {}, "true", "false" %>
        <span>緊急時（自然災害・感染症対策等）</span><br>
        <%= f.check_box :primary_sector, {}, "true", "false" %>
        <span>農林漁業者向け</span><br>
        <%= f.check_box :other_sector, {}, "true", "false" %>
        <span>その他事業者向け</span><br>
        <%= f.check_box :emigration, {}, "true", "false" %>
        <span>移住者向け</span><br>
        <%= f.check_box :senior, {}, "true", "false" %>
        <span>高齢者向け</span><br>
        <%= f.check_box :parenting, {}, "true", "false" %>
        <span>子育て世帯向け</span><br>
        <%= f.check_box :other, {checked: true}, "true", "false" %>
        <span>それ以外</span>
        <br>
        
        <% end %>
      <%= pref.submit "マスタ投稿", class: "btn btn-primary btn-block btn-login" %>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="col-md-10 col-md-offset-1 col-xs-12 city_background">
    <h3 class="center"><%= link_to "市",admin_index_pref_path %></h3>
    <%= form_with(model: @cities, url: admin_city_topic_post_user_path(@user), local: true) do |city| %>

      <div class="col-md-10 col-md-offset-1 col-xs-12">
        <%= city.label "実施官公庁名" %>
        <%= city.collection_select :pref, Pref.all, :id, :pref_name, {prompt: "選択して下さい"} %>
        <%= render partial: 'cities', locals: {pref_id: Pref.first.id} %>
        <br>

        <%= city.fields_for "city_topics[]", @city_topic do |f| %>

        <%= f.label "施作名" %>
        <%= f.text_field :title, class: 'form-control' %>

        <%= f.label "実施期間" %>
        <%= f.text_field :period, class: 'form-control' %>

        <%= f.label "実施内容" %>
        <%= f.text_area :content, class: 'form-control' %>

        <%= f.label "対象者" %>
        <%= f.text_field :target, class: 'form-control' %>

        <%= f.label "受付窓口" %>
        <%= f.text_field :counter, class: 'form-control' %>

        <%= f.label "リンク" %>
        <%= f.text_field :link, class: 'form-control' %>

      </div>

      <div class="col-md-10 col-md-offset-1 col-xs-12">
        <%= f.label "カテゴリー" %><br>
        <%= f.check_box :emergency, {}, "true", "false" %>
        <span>緊急時（自然災害・感染症対策等）</span><br>
        <%= f.check_box :primary_sector, {}, "true", "false" %>
        <span>農林漁業者向け</span><br>
        <%= f.check_box :other_sector, {}, "true", "false" %>
        <span>その他事業者向け</span><br>
        <%= f.check_box :emigration, {}, "true", "false" %>
        <span>移住者向け</span><br>
        <%= f.check_box :senior, {}, "true", "false" %>
        <span>高齢者向け</span><br>
        <%= f.check_box :parenting, {}, "true", "false" %>
        <span>子育て世帯向け</span><br>
        <%= f.check_box :other, {checked: true}, "true", "false" %>
        <span>それ以外</span>
        <br>
        
        <% end %>
      <%= city.submit "マスタ投稿", class: "btn btn-primary btn-block btn-login" %>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<% provide(:title,"Edit") %>
<% provide(:class_text, 'user--edit') %>
<% provide(:button_text, '更新') %>
<h1>アカウント情報の更新</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
  <div class="col-md-6 col-md-offset-3">
  <% if current_user?(@user) %>
    <%= link_to "削除", @user, method: :delete,
      data: { confirm:"削除してよろしいですか？" }, class: "btn btn-danger" %>
  <% end %>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All Users') %>
<h1><%= @title %></h1>

<div class="row container">
  <div class="col-md-4 col-md-offset-8">
    <p>ユーザー名検索</p>
    <%= form_with(url: users_path, method: :get, local: true) do |f| %>
      <%= f.text_field :search %>
      <%= f.submit '検索', :name => nil %><%= link_to 'Clear', users_path, :search => nil %>
    <% end %>
  </div>
</div>

<div class="col-md-10 col-md-offset-1">
  <%= will_paginate %>
  <table class="table table-condensed table-hover" id="table-users">
    <thead>
      <tr>
        <th><%= User.human_attribute_name :name %></th></th>
      </tr>
    </thead>
        
    <% @user.each do |user| %>
      <tr>
        <td>
          <% if current_user.admin? %>
            <%= link_to user.name, user %>
          <% else %>
            <%= user.name %>
          <% end %>
        </td>
        <td class="center"></td>
        <td class="center">
          <% if current_user.admin? && !current_user?(user) %>
            <%= link_to "削除", user, method: :delete,
                data: { confirm:"削除してよろしいですか？" }, class: "btn btn-danger" %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>
  <%= will_paginate %>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:class_text, 'signup') %>
<% provide(:button_text, '新規作成') %>
<h1>アカウント作成</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <div class="alert alert-danger">
          入力エラーが<%= @user.errors.count %>件ありました。
        </div>
        <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    
    <%= form_with model: @user, url: users_path(@user), local: true, method: :post do |f| %>
      <%= f.label "名前", class: "label-#{yield(:class_text)}" %>
      <%= f.text_field :name, class: "form-control" %>
      
      <%= f.label "メールアドレス", class: "label-#{yield(:class_text)}" %>
      <%= f.email_field :email, class: "form-control" %>
      
      <%= f.label "パスワード", class: "label-#{yield(:class_text)}" %>
      <%= f.password_field :password, class: "form-control" %>
      
      <%= f.submit "新規作成", class: "btn btn-primary btn-block btn-signup btn-#{yield(:button_text)}" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<h2><%= @user.name %></h2>
<div>
  <table class="table table-bordered table-condensed user-table">
    <tr>
      <td>ユーザーネーム</td>
      <td><%= @user.name %></td>
    </tr>

    <tr>
      <td>メールアドレス</td>
      <td><%= @user.email %></td>
    </tr>

    <tr>
      <td>ユーザーID</td>
      <td><%= @user.id %></td>
    </tr>
  </table>
</div>