config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'static_pages#top'
  get  '/signup', to: 'users#new'

  get     '/login', to: 'sessions#new'
  post    '/login', to: 'sessions#create'
  delete  '/logout', to: 'sessions#destroy'

  resources :users do
    member do
      get 'admin_post'
      post 'admin_pref_topic_post'
      post 'admin_city_topic_post'
    end
    resources :drafts
  end

  resources :gov_topics

  resources :prefs do
    member do
      get 'admin_index'
    end
    collection do
      get 'cities_select' # /prefs/cities_select
    end
    collection {post :import}
      resources :pref_topics
      resources :cities do
        member do
          get 'admin_index'
        end
        collection {post :import}
        resources :city_topics
      end
  end
  #get 'city_topics/new'
  #get 'city_topics/edit'
  #get 'city_topics/show'
  #get 'city_topics/index'
  #get 'pref_topics/new'
  #get 'pref_topics/edit'
  #get 'pref_topics/show'
  #get 'pref_topics/index'
  #get 'prefs/index'
  #get 'prefs/show'
  #get 'gov_topics/new'
  #get 'gov_topics/edit'
  #get 'gov_topics/show'
  #get 'gov_topics/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/draft.rb
class Draft < ApplicationRecord
  belongs_to :user
  validates :name, presence: true, length: { maximum: 50 }
  validates :title, presence: true, length: { maximum: 50 }
  validates :period, presence: true, length: { maximum: 70 }
  validates :content, presence: true, length: { maximum: 300 }
  validates :target, presence: true, length: { maximum: 50 }
  validates :counter, presence: true, length: { maximum: 50 }
  validates :link, presence: true, length: { maximum: 500 }
  validates :comment, length: { maximum: 100 }
end

app/controllers/drafts_controller.rb
class DraftsController < ApplicationController

  def index
    @user = User.find(params[:user_id])
    @drafts = current_user.admin? ? Draft.all : Draft.where(user_id: @user.id)
  end

  def new
    @user = User.find(params[:user_id])
    @draft = @user.drafts.new
  end

  def create
    @user = User.find(params[:user_id])
    @draft = @user.drafts.new(draft_params)
    if @draft.save
      flash[:success] = '投稿を送信しました。'
      redirect_to root_url
    else
      flash.now[:danger] = '投稿の送信ができませんでした。'
      render :new
    end
  end

  def edit
  end

  def update
    @user = User.find(params[:user_id])
    @draft = @user.drafts.find(params[:id])
    if @draft.update_attributes!(draft_params)
      @draft.update(draft_status: "更新申請中です")
      flash[:info] = "投稿を更新して送信しました。"
      redirect_to root_url
    else  
      flash[:danger] = "投稿の更新に失敗しました。"
      redirect_to root_url
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    @draft = Draft.find(params[:id])
  end

  private

    def draft_params
      params.require(:draft).permit(:name, :title, :period, :content, :target, :counter, :link, :emergency, :primary_sector, :other_sector, :emigration, :senior, :parenting, :other, :select)
    end
end

app/helpers/drafts_helper.rb
module DraftsHelper
end

app/views/drafts/_form.html.erb
<div class="col-md-10 col-md-offset-1 col-xs-12">
<%= form_with url: user_draft_path(current_user, draft), method: :patch, local: true do |d| %>
  <h3>編集する</h3><br>
  <%= d.label "実施官公庁名", class: "label-draft" %>
  <%= d.text_field :name, placeholder: "（例）◯◯省、◯◯庁、××県、××県△△市 など", class: 'form-control' %>

  <%= d.label "施作名", class: "label-draft" %>
  <%= d.text_field :title, placeholder: "（例）◯◯補助金事業、令和×年度××助成金事業、△△減免 など", class: 'form-control' %>

  <%= d.label "実施期間", class: "label-draft" %>
  <%= d.text_field :period, placeholder: "（例）令和◯年◯月◯日〜令和×年×月×日、予定数に達するまで随時受付 など", class: 'form-control' %>

  <%= d.label "実施内容", class: "label-draft" %>
  <%= d.text_area :content, placeholder: "（例）◯◯を目的に、××の方を対象に最大△△万円を助成する。（申し込み時に審査が必要） など", class: 'form-control' %>

  <%= d.label "対象者", class: "label-draft" %>
  <%= d.text_field :target, placeholder: "（例）◯◯歳以上××歳未満の方、申請時に△△内に住民票がある方 など", class: 'form-control' %>

  <%= d.label "受付窓口", class: "label-draft" %>
  <%= d.text_field :counter, placeholder: "（例）各市町村窓口、◯◯県◯◯地域センター、××市△△課 など", class: 'form-control' %>

  <%= d.label "リンク", class: "label-draft" %>
  <%= d.text_field :link, placeholder: "（例）https://www.hoge.lg.jp/fugafuga.html （該当ページリンクを貼り付けてください）", class: 'form-control' %>

</div>

<div class="col-md-10 col-md-offset-1 col-xs-12">
  <%= d.label "カテゴリー", class: "label-draft" %><br>
  <%= d.check_box :emergency, {}, "true", "false" %>
  <span>緊急時（自然災害・感染症対策等）</span><br>
  <%= d.check_box :primary_sector, {}, "true", "false" %>
  <span>農林漁業者向け</span><br>
  <%= d.check_box :other_sector, {}, "true", "false" %>
  <span>その他事業者向け</span><br>
  <%= d.check_box :emigration, {}, "true", "false" %>
  <span>移住者向け</span><br>
  <%= d.check_box :senior, {}, "true", "false" %>
  <span>高齢者向け</span><br>
  <%= d.check_box :parenting, {}, "true", "false" %>
  <span>子育て世帯向け</span><br>
  <%= d.check_box :other, {checked: true}, "true", "false" %>
  <span>それ以外</span>
  <br>
  <%= d.label "どの官公庁が関わっていますか？", class: "label-draft" %><br>
  <%= d.radio_button :select, "国", checked: true %>政府が関わっている<br> <%= d.radio_button :select, "県" %>都道府県独自<br> <%= d.radio_button :select, "市" %>市町村独自<br>

  <% if current_user.admin? %>
    <%= d.label "コメント", class: "label-draft" %>
    <%= d.text_field :comment, placeholder: "ご投稿ありがとうございます！", class: 'form-control' %>

    <%= d.label "承認状況" %>
    <%= d.text_field :draft_status, placeholder: "申請中です、承認・更新を行いました（一部校正）、申し訳ありませんが再提出をお願いいたします", class: 'form-control' %>
  <% end %>

  <%= d.submit "更新", class: "btn btn-primary btn-block btn-login" %>
<% end %>
</div>

app/views/drafts/edit.html.erb
<h1>Drafts#edit</h1>
<p>Find me in app/views/drafts/edit.html.erb</p>

app/views/drafts/index.html.erb
<% provide(:title, 'All Drafts') %>
<h1>投稿一覧</h1>

<div class="col-md-10 col-md-offset-1">
  <% if @drafts.empty? %>
    <p>まだ投稿はありません</p>
  <% else %>
    <table class="table table-condensed table-hover" id="table-users">
      <% @drafts.each do |draft| %>
        <tr>
          <td><%= draft.name %>: <%= draft.title %>
            <% if current_user?(@user) %>
              <%= link_to "削除", user_draft_path(current_user, draft), method: :delete, class: "btn btn-sm btn-danger",
                  data: { confirm:"削除してよろしいですか？" } %><br>
              <div class="panel-group">
                <div class="panel panel-default">
                  <div class="panel-heading">
                    <h4 class="panel-title">
                      <a data-toggle="collapse" href="#collapse<%= draft.id %>"><button type="submit" class="btn btn-info">詳細・編集</button></a>
                    </h4>
                  </div>
                  
                  <div id="collapse<%= draft.id %>" class="panel-collapse collapse">
                    <ul class="list-group">
                      <table class="table table-bordered table-condensed table-hover">
                        <tr>
                          <td>実施期間</td>
                          <td><%= draft.period %></td>
                        </tr>
                        <tr>
                          <td>実施内容</td>
                          <td><%= draft.content %></td>
                        </tr>
                        <tr>
                          <td>対象者</td>
                          <td><%= draft.target %></td>
                        </tr>
                        <tr>
                          <td>受付窓口</td>
                          <td><%= draft.counter %></td>
                        </tr>
                        <tr>
                          <td>リンク</td>
                          <td><%= draft.link %></td>
                        </tr>
                        <tr>
                          <td>承認状況</td>
                          <td><%= draft.draft_status %></td>
                        </tr>
                        <tr>
                          <td>管理者より</td>
                          <td><%= draft.comment %></td>
                        </tr>
                      </table>
                    </ul>

                    <div class="col-md-10 col-md-offset-1 col-xs-12">
                      <%= form_with model: draft, url: user_draft_path(current_user, draft), method: :patch, local: true do |d| %>
                        <h3>編集する</h3><br>
                        <%= d.label "実施官公庁名", class: "label-draft" %>
                        <%= d.text_field :name, placeholder: "（例）◯◯省、◯◯庁、××県、××県△△市 など", class: 'form-control' %>

                        <%= d.label "施作名", class: "label-draft" %>
                        <%= d.text_field :title, placeholder: "（例）◯◯補助金事業、令和×年度××助成金事業、△△減免 など", class: 'form-control' %>

                        <%= d.label "実施期間", class: "label-draft" %>
                        <%= d.text_field :period, placeholder: "（例）令和◯年◯月◯日〜令和×年×月×日、予定数に達するまで随時受付 など", class: 'form-control' %>

                        <%= d.label "実施内容", class: "label-draft" %>
                        <%= d.text_area :content, placeholder: "（例）◯◯を目的に、××の方を対象に最大△△万円を助成する。（申し込み時に審査が必要） など", class: 'form-control' %>

                        <%= d.label "対象者", class: "label-draft" %>
                        <%= d.text_field :target, placeholder: "（例）◯◯歳以上××歳未満の方、申請時に△△内に住民票がある方 など", class: 'form-control' %>

                        <%= d.label "受付窓口", class: "label-draft" %>
                        <%= d.text_field :counter, placeholder: "（例）各市町村窓口、◯◯県◯◯地域センター、××市△△課 など", class: 'form-control' %>

                        <%= d.label "リンク", class: "label-draft" %>
                        <%= d.text_field :link, placeholder: "（例）https://www.hoge.lg.jp/fugafuga.html （該当ページリンクを貼り付けてください）", class: 'form-control' %>

                      </div>

                      <div class="col-md-10 col-md-offset-1 col-xs-12">
                        <%= d.label "カテゴリー", class: "label-draft" %><br>
                        <%= d.check_box :emergency, {}, "true", "false" %>
                        <span>緊急時（自然災害・感染症対策等）</span><br>
                        <%= d.check_box :primary_sector, {}, "true", "false" %>
                        <span>農林漁業者向け</span><br>
                        <%= d.check_box :other_sector, {}, "true", "false" %>
                        <span>その他事業者向け</span><br>
                        <%= d.check_box :emigration, {}, "true", "false" %>
                        <span>移住者向け</span><br>
                        <%= d.check_box :senior, {}, "true", "false" %>
                        <span>高齢者向け</span><br>
                        <%= d.check_box :parenting, {}, "true", "false" %>
                        <span>子育て世帯向け</span><br>
                        <%= d.check_box :other, {checked: true}, "true", "false" %>
                        <span>それ以外</span>
                        <br>
                        <%= d.label "どの官公庁が関わっていますか？", class: "label-draft" %><br>
                        <%= d.radio_button :select, "国", checked: true %>政府が関わっている<br> <%= d.radio_button :select, "県" %>都道府県独自<br> <%= d.radio_button :select, "市" %>市町村独自<br>

                        <% if current_user.admin? %>
                          <%= d.label "コメント", class: "label-draft" %>
                          <%= d.text_field :comment, placeholder: "ご投稿ありがとうございます！", class: 'form-control' %>

                          <%= d.label "承認状況" %>
                          <%= d.text_field :draft_status, placeholder: "申請中です、承認・更新を行いました（一部校正）、申し訳ありませんが再提出をお願いいたします", class: 'form-control' %>
                        <% end %>

                        <%= d.submit "更新", class: "btn btn-primary btn-block btn-login" %>
                      <% end %>
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
          </td>
        </tr>
      <% end %>
    </table>
  <% end %> 
</div>

app/views/drafts/new.html.erb
<% provide(:title, "New draft") %>
<h1>投稿ページ</h1>

<div class="row">

  <%= form_with(model: @draft, url: user_drafts_path(@user, @draft), method: :post, local: true) do |f| %>
    <%#= f.fields_for "drafts[]", @draft do |d| %>

    <div class="col-md-10 col-md-offset-1 col-xs-12">
      <%= f.label "実施官公庁名", class: "label-draft" %>
      <%= f.text_field :name, placeholder: "（例）◯◯省、◯◯庁、××県、××県△△市 など", class: 'form-control' %>

      <%= f.label "施作名", class: "label-draft" %>
      <%= f.text_field :title, placeholder: "（例）◯◯補助金事業、令和×年度××助成金事業、△△減免 など", class: 'form-control' %>

      <%= f.label "実施期間", class: "label-draft" %>
      <%= f.text_field :period, placeholder: "（例）令和◯年◯月◯日〜令和×年×月×日、予定数に達するまで随時受付 など", class: 'form-control' %>

      <%= f.label "実施内容", class: "label-draft" %>
      <%= f.text_area :content, placeholder: "（例）◯◯を目的に、××の方を対象に最大△△万円を助成する。（申し込み時に審査が必要） など", class: 'form-control' %>

      <%= f.label "対象者", class: "label-draft" %>
      <%= f.text_field :target, placeholder: "（例）◯◯歳以上××歳未満の方、申請時に△△内に住民票がある方 など", class: 'form-control' %>

      <%= f.label "受付窓口", class: "label-draft" %>
      <%= f.text_field :counter, placeholder: "（例）各市町村窓口、◯◯県◯◯地域センター、××市△△課 など", class: 'form-control' %>

      <%= f.label "リンク", class: "label-draft" %>
      <%= f.text_field :link, placeholder: "（例）https://www.hoge.lg.jp/fugafuga.html （該当ページリンクを貼り付けてください）", class: 'form-control' %>

    </div>

    <div class="col-md-10 col-md-offset-1 col-xs-12">
      <%= f.label "カテゴリー", class: "label-draft" %><br>
      <%= f.check_box :emergency, {}, "true", "false" %>
      <span>緊急時（自然災害・感染症対策等）</span><br>
      <%= f.check_box :primary_sector, {}, "true", "false" %>
      <span>農林漁業者向け</span><br>
      <%= f.check_box :other_sector, {}, "true", "false" %>
      <span>その他事業者向け</span><br>
      <%= f.check_box :emigration, {}, "true", "false" %>
      <span>移住者向け</span><br>
      <%= f.check_box :senior, {}, "true", "false" %>
      <span>高齢者向け</span><br>
      <%= f.check_box :parenting, {}, "true", "false" %>
      <span>子育て世帯向け</span><br>
      <%= f.check_box :other, {checked: true}, "true", "false" %>
      <span>それ以外</span>
      <br>
      <%= f.label "どの官公庁が関わっていますか？", class: "label-draft" %><br>
      <%= f.radio_button :select, "国", checked: true %>政府が関わっている<br> <%= f.radio_button :select, "県" %>都道府県独自<br> <%= f.radio_button :select, "市" %>市町村独自

      
    <%= f.submit "投稿", class: "btn btn-primary btn-block btn-login" %>
      <%# end %>
  </div>
  <% end %>
  
</div>