config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'static_pages#top'
  get  '/signup', to: 'users#new'

  get     '/login', to: 'sessions#new'
  post    '/login', to: 'sessions#create'
  delete  '/logout', to: 'sessions#destroy'

  resources :users do
    member do
      get 'admin_post'
      post 'admin_pref_topic_post'
      post 'admin_city_topic_post'
    end
    resources :drafts
  end

  resources :gov_topics

  resources :prefs do
    member do
      get 'admin_index'
    end
    collection do
      get 'cities_select' # /prefs/cities_select
    end
    collection {post :import}
      resources :pref_topics
      resources :cities do
        member do
          get 'admin_index'
        end
        collection {post :import}
        resources :city_topics
      end
  end
  #get 'city_topics/new'
  #get 'city_topics/edit'
  #get 'city_topics/show'
  #get 'city_topics/index'
  #get 'pref_topics/new'
  #get 'pref_topics/edit'
  #get 'pref_topics/show'
  #get 'pref_topics/index'
  #get 'prefs/index'
  #get 'prefs/show'
  #get 'gov_topics/new'
  #get 'gov_topics/edit'
  #get 'gov_topics/show'
  #get 'gov_topics/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse", id="header">
  <div class="container">
    <%= link_to "補助金・助成金・減免検索ツール", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "トップ", root_path %></li>
        <% if logged_in? %>
          <% if current_user.admin? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                メニュー <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "マスタ投稿", admin_post_user_path(current_user) %></li>
                <li><%= link_to "投稿依頼一覧", user_drafts_path(current_user), method: :get %></li>
                <li><%= link_to "投稿者一覧", users_path, method: :get %></li>
                <li><%= link_to "管理者設定", edit_user_path(current_user) %></li>
                <li class="divider"></li>
              <li>
                 <%= link_to "ログアウト", logout_path, method: :delete %>
              </li>
          <% end %>
          <% unless current_user.admin? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                メニュー <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "新規投稿", new_user_draft_path(current_user), method: :get %></li>
                <li><%= link_to "投稿ログ一覧", user_drafts_path(current_user), method: :get %></li>
                <li><%= link_to "ユーザー設定", edit_user_path(current_user) %></li>
                <li class="divider"></li>
              <li>
                <%= link_to "ログアウト", logout_path, method: :delete %>
              </li>
              </ul>
            </li>
          <% end %>
        <% else %>
          <li><%= link_to "ログイン", login_path, method: :get %></li>
        <% end %>
      </ul>
    </nav>
  </div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <div><%= render 'layouts/header' %></div>
    <div class="container">
      <% flash.each do |message_type, msg| %>
        <div class="alert alert-<%= message_type %>"><%= msg.html_safe %></div>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>